---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: latest
  become: yes
- name: Install git
  apt:
    name: git
    state: latest
  become: yes
- name: Configure dnsmasq
  copy:
    src: "{{ role_path }}/files/10-consul"
    dest: "/etc/dnsmasq.d/10-consul"
  become: yes
# See https://medium.com/zendesk-engineering/making-docker-and-consul-get-along-5fceda1d52b9
- name: Setup Dummy interface
  block:
  - name: Copy systemd files
    copy:
      src: "{{ role_path }}/files/dummy/{{ item }}"
      dest: "/etc/systemd/network/{{ item }}"
    with_items:
      - dummy0.netdev
      - dummy0.network
    become: yes
  - name: Enable systemd-networkd.service
    shell: "systemctl enable systemd-networkd.service"
    become: yes
- name: Clone Consul module
  git:
    repo: "{{ consul_module_repo }}"
    dest: "/tmp/terraform-aws-consul"
    version: "{{ consul_module_version }}"
- name: Install Consul
  shell: "/tmp/terraform-aws-consul/modules/install-consul/install-consul --version {{ consul_version }}"
- name: "Copy Consul configuration"
  copy:
    src: "{{ role_path }}/files/config/"
    dest: "/opt/consul/config"
  become: yes
- name: "Copy Consul template sub-configurations"
  template:
    src: "{{ role_path }}/files/templates/{{ item }}"
    dest: "/opt/consul/config/{{ item }}"
  vars:
    enable_syslog: "{{ consul_enable_syslog }}"
  with_items:
  - syslog.hcl
  become: yes
