---
# Version of Consul template to install
consul_template_version: "0.19.5"
# User to run consul_template under
consul_template_user: root
# Base path to install
base_path: "/opt/consul-template"
# Path to Upstart binary
initctl: "/sbin/initctl"
